/**
 * Global Error Handler Middleware
 * Intent: Provide a centralized, secure catch-all for all application errors to 
 * prevent leaking sensitive stack traces and ensure a consistent JSON error format.
 * Flow: 
 * 1. Log the error with high-context metadata (Request ID, Method, Path).
 * 2. Distinguish between operational errors (AppError) and unexpected system crashes.
 * 3. Sanitize error messages based on the environment (Production vs. Development).
 * 4. Inject the unique Request ID into every error response for easier support correlation.
 */

const { AppError } = require('../utils/errors');
const log = require('../utils/log');

/**
 * Main Error Dispatcher
 * Intent: Handle the final stage of the request/response lifecycle when an error occurs.
 * Flow: 
 * - Captures the error object from the 'next(err)' pipeline.
 * - Logs detailed stack traces in development but suppresses them in production.
 * - Formats response body with 'success: false' and relevant error codes.
 */
function errorHandler(err, req, res, next) {
  void next;

  const config = require('../config');
  
  // Intent: Maintain a searchable audit trail in logs.
  // Flow: Map the error to the unique 'req.id' generated by the requestIdMiddleware.
  log.error('ERROR_HANDLER', 'Error occurred', {
    requestId: req.id, 
    path: req.path,
    method: req.method,
    error: err.message,
    stack: config.server.isDevelopment ? err.stack : undefined
  });

  // Intent: Handle known operational errors (e.g., balance insufficient, invalid address).
  // Flow: Serialize the custom AppError and attach the Request ID to the response body.
  if (err instanceof AppError) {
    const errorBody = err.toJSON();
    errorBody.error.requestId = req.id; 
    return res.status(err.statusCode).json(errorBody);
  }

  // Intent: Handle 500 Internal Server Errors and Validation Errors.
  // Flow: Determine status code -> Check for Joi/Schema validation names -> Apply production masking.
  const statusCode = err.statusCode || err.status || 500;
  const isValidationError = err.name === 'ValidationError';
  res.status(statusCode).json({
    success: false,
    error: {
      code: isValidationError ? 'VALIDATION_ERROR' : 'INTERNAL_ERROR',
      message: config.server.isProduction && !isValidationError
        ? 'An unexpected error occurred' 
        : err.message,
      requestId: req.id, 
      timestamp: new Date().toISOString()
    }
  });
}

/**
 * 404 Not Found Handler
 * Intent: Gracefully catch requests to undefined routes.
 * Flow: Triggered when no routes in app.js match the requested URL. Returns 404 JSON.
 */
function notFoundHandler(req, res) {
  res.status(404).json({
    success: false,
    error: {
      code: 'ENDPOINT_NOT_FOUND',
      message: `Endpoint not found: ${req.method} ${req.path}`,
      timestamp: new Date().toISOString()
    }
  });
}

module.exports = {
  errorHandler,
  notFoundHandler
};